image: node:12.14.0

stages:
  - setup
  - dockerfile
  - deploy

Setup:
  stage: setup
  environment: staging
  script:
    - node ./scripts/generate-env-from-system.js
  only:
    - /^release-v\d+\.\d+\.\d+$/

Dockerfile:
  stage: dockerfile
  environment: staging
  image: docker:git
  services:
    - docker:dind
  script:
    # Deploy to Docker Registry
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH .
    - docker tag registry.gitlab.com/$CI_PROJECT_PATH registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA
    - docker push registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  only:
    - /^release-v\d+\.\d+\.\d+$/

Deploy-Staging:
  stage: deploy
  environment: staging
  script:
    - echo "====== Deploy to production server ======"
    - apk update && apk upgrade
    - apk add git openssh bash
    # Add target server`s secret key
    - mkdir ~/.ssh
    - echo $TARGET_SERVER_SECRET_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "Test ssh connection"
    - ssh -o StrictHostKeyChecking=no -T "thuedo@$TARGET_SERVER_HOST"

    # Deploy to server
    - ssh -o StrictHostKeyChecking=no -T "thuedo@$TARGET_SERVER_HOST" "docker pull registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA"
    - ssh -o StrictHostKeyChecking=no -T "thuedo@$TARGET_SERVER_HOST" "docker service update node-server --image registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA --with-registry-auth --force --detach"
  only:
    - /^release-v\d+\.\d+\.\d+$/
