image: node:12.14.0

cache:
  paths:
    - node_modules/
    - dist/

stages:
  - setup
  - build
  - deploy

Setup:
  stage: setup
  script:
    - npm install
    - npm install --only=dev
  only:
    - /^release-v\d+\.\d+\.\d+$/
  artifacts:
    paths:
      - node_modules/

Build:
  stage: build
  script: npm run build
  only:
    - /^release-v\d+\.\d+\.\d+$/
  artifacts:
    paths:
      - dist/

Deploy-Staging:
  stage: deploy
  environment: staging
  image: keymetrics/pm2:15-alpine
  script:
    - echo "====== Deploy to production server ======"
    - apk update && apk upgrade
    - apk add git openssh bash
    # Add target server`s secret key
    - mkdir ~/.ssh
    - echo $TARGET_SERVER_SECRET_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "Test ssh connection"
    - ssh -o StrictHostKeyChecking=no -T "ubuntu@$TARGET_SERVER_HOST"
    # Delploy
    - echo "Setup tagget server directories"
    - pm2 deploy ecosystem.config.js production setup 2>&1 || true
    - echo "make deploy"
    - pm2 deploy ecosystem.config.js production
  only:
    - /^release-v\d+\.\d+\.\d+$/
