image: docker:stable

cache:
  paths:
    - .env

stages:
  - setup
  - dockerfile
  - deploy

Setup:
  stage: setup
  image: node:12.15.0-slim
  environment: staging
  script:
    - node ./scripts/generate-env-from-system.js
  only:
    - /^release-v\d+\.\d+\.\d+$/

Dockerfile-Staging:
  stage: dockerfile
  environment: staging
  services:
    - docker:dind
  script:
    # Deploy to Docker Registry
    # - cat .env
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH .
    - docker tag registry.gitlab.com/$CI_PROJECT_PATH registry.gitlab.com/$CI_PROJECT_PATH:staging-$CI_COMMIT_SHA
    - docker push registry.gitlab.com/$CI_PROJECT_PATH:staging-$CI_COMMIT_SHA
  only:
    - /^release-v\d+\.\d+\.\d+$/

Deploy-Staging:
  stage: deploy
  environment: staging
  script:
    - echo "====== Deploy to production server ======"
    - apk update && apk upgrade
    - apk add git openssh bash
    # Add target server`s secret key
    - mkdir ~/.ssh
    - echo $TARGET_SERVER_SECRET_KEY_BASE64 | base64 -d > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
    - echo "Test ssh connection"
    - ssh -o StrictHostKeyChecking=no -T "thuedo@$TARGET_SERVER_HOST"

    # Deploy to server
    - ssh -o StrictHostKeyChecking=no -T "thuedo@$TARGET_SERVER_HOST" "docker login registry.gitlab.com -u thuedo-stag-depoy -p $GITLAB_DEPLOY_TOKEN"
    - ssh -o StrictHostKeyChecking=no -T "thuedo@$TARGET_SERVER_HOST" "docker pull registry.gitlab.com/$CI_PROJECT_PATH:staging-$CI_COMMIT_SHA"
    # Delete old containers && old images
    - ssh -o StrictHostKeyChecking=no -T "thuedo@$TARGET_SERVER_HOST" "docker stop thuedo_api_app || true && docker rm thuedo_api_app || true && docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'registry.gitlab.com/thuedo1/web-api') || true"
    - ssh -o StrictHostKeyChecking=no -T "thuedo@$TARGET_SERVER_HOST" "docker run -d --net="host" --restart always  --name thuedo_api_app --add-host=host.docker.internal:127.0.0.1 registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA"
  only:
    - /^release-v\d+\.\d+\.\d+$/
