export enum Permission {
  CANCEL = 'CANCEL',
  APPROVE = 'APPROVE',
  DECLINE = 'DECLINE',
  START = 'START',
  COMPLETE = 'COMPLETE',
  ADD_COMMENT = 'ADD_COMMENT',
  VIEW_LENDER_INFO = 'VIEW_LENDER_INFO',
  VIEW_REQUEST_RENT_OWNER_INFO = 'VIEW_REQUEST_RENT_OWNER_INFO'
}
