export enum OrgActivityLogType {
  CreateRentingOrder = 'CreateRentingOrder',
  UpdateRentingOrder = 'UpdateRentingOrder',
  ChangeStatusRentingOrder = 'ChangeStatusRentingOrder',
  DeleteReningOrder = 'DeleteRentingOrder',
  CreateItem = 'CreateItem',
  UpdateItem = 'UpdateItem',
  DeleteItem = 'DeleteItem',
  CreateCustomer = 'CreateCustomer',
  UpdateCustomer = 'UpdateCustomer',
  CreateRole = 'CreateRole',
  UpdateRole = 'UpdateRole',
  UpdateOrgInformation = 'UpdateOrgInformation',
  AddCategory = 'AddCategory',
  DeleteCategory = 'DeleteCategory',
  UpdateCategory = 'UpdateCategory',
  CreatePayForRentingOrder = 'CreatePayForRentingOrder',
  CreateRefundForRentingOrder = 'CreateRefundForRentingOrder',
  CreateDamagesPayForRentingItemOrder = 'CreateDamagesPayForRentingItemOrder',
  CreateDamagesRefundForRentingItemOrder = 'CreateDamagesRefundForRentingItemOrder',
}
