export enum Permission {
  ADD_TO_MY_LIST = 'ADD_TO_MY_LIST',
  CHAT_WITH_SHOP_OWNER = 'CHAT_WITH_SHOP_OWNER',
  CREATE_RENTING_REQUEST = 'CREATE_RENTING_REQUEST',
  VIEW_RENTING_REQUEST_BOX = 'VIEW_RENTING_REQUEST_BOX',
  VIEW_CHAT_WITH_SHOP_OWNER_BOX = 'VIEW_CHAT_WITH_SHOP_OWNER_BOX',
  EDIT_ITEM = 'EDIT_ITEM',
}
