export enum Permission {
  ADD_TO_MY_LIST = 'ADD_TO_MY_LIST',
  CHAT_WITH_SHOP_OWNER = 'CHAT_WITH_SHOP_OWNER',
  CREATE_RENTING_REQUEST = 'CREATE_RENTING_REQUEST',
  VIEW_RENTING_REQUEST_BOX = 'VIEW_RENTING_REQUEST_BOX',
  VIEW_CHAT_WITH_SHOP_OWNER_BOX = 'VIEW_CHAT_WITH_SHOP_OWNER_BOX',
  EDIT_ITEM = 'EDIT_ITEM',
  CHANGE_TO_PUBLISHED = 'CHANGE_TO_PUBLISHED',
  CHANGE_TO_DRAFT = 'CHANGE_TO_DRAFT',
  CHANGE_TO_BLOCKED = 'CHANGE_TO_BLOCKED',
  APPROVE_ITEM = 'APPROVE_ITEM',
  REJECT_ITEM = 'REJECT_ITEM',
}
